import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Database, Lock, Zap, HardDrive, Radio, Box, PiIcon as Api } from 'lucide-react'

function WaveBackground() {
  return (
    <div className="absolute inset-0 overflow-hidden -translate-y-24">
      <svg
        className="absolute w-full h-full opacity-20"
        viewBox="0 0 1000 1000"
        preserveAspectRatio="none"
      >
        <path
          d="M 0 700 Q 400 600 800 750 T 1600 700"
          fill="none"
          stroke="rgb(22, 163, 74)"
          strokeWidth="2"
          className="animate-wave"
        />
        <path
          d="M 0 750 Q 300 650 600 800 T 1200 750"
          fill="none"
          stroke="rgb(22, 163, 74)"
          strokeWidth="2"
          className="animate-wave"
          style={{ animationDelay: "0.2s" }}
        />
        <path
          d="M 0 800 Q 400 700 800 850 T 1600 800"
          fill="none"
          stroke="rgb(22, 163, 74)"
          strokeWidth="2"
          className="animate-wave"
          style={{ animationDelay: "0.4s" }}
        />
        <path
          d="M 0 850 Q 300 750 600 900 T 1200 850"
          fill="none"
          stroke="rgb(22, 163, 74)"
          strokeWidth="2"
          className="animate-wave"
          style={{ animationDelay: "0.6s" }}
        />
      </svg>
    </div>
  )
}

export default function Component() {
  const features = [
    {
      icon: <Database className="h-6 w-6" />,
      title: "Commodity & Energy Database",
      description: "Provide a robust, project-specific database foundation for managing and analyzing multi-source data relevant to commodity and energy trading.",
      bulletPoints: ["100% Portable", 
        "Built-in Access Control", 
        "Highly Scalable"],
      illustration: (
        <div>
          
        </div>
      ),
      wide: true
    },
    {
      icon: <Lock className="h-6 w-6" />,
      title: "Trading Access Management",
      description: "Add user accounts and logins with fine-grained permissions to secure both sensitive data and trading strategies.",
      illustration: (
        <div>
          
        </div>
      )
    },
    {
      icon: <Zap className="h-6 w-6" />,
      title: "Dynamic Data Processing Engine",
      description: "Write custom logic without deploying or managing dedicated servers, enabling real-time data processing for trading insights.",
      illustration: (
        <div>
          
        </div>
      )
    },
    {
      icon: <HardDrive className="h-6 w-6" />,
      title: "Massive Data Storage",
      description: "Centralize and manage diverse data—from satellite imagery to IoT sensor feeds—to support your quantitative trading and analysis efforts.",
      illustration: (
        <div>
          
        </div>
      )
    },
    {
      icon: <Radio className="h-6 w-6" />,
      title: "Real-Time Data Synchronization",
      description: "Enable multi-user collaboration and real-time market data updates, helping you stay on top of sudden market movements.",
      illustration: (
        <div>
          
        </div>
      )
    },
    {
      icon: <Box className="h-6 w-6" />,
      title: "Quantitative Vector Search",
      description: "Efficiently store, index, and search vector data generated by machine learning or NLP models for deeper quantitative insights.",
      badges: ["OpenAI", "Hugging Face"],
      illustration: (
        <div>
          
        </div>
      )
    },
    {
      icon: <Api className="h-6 w-6" />,
      title: "Data APIs",
      description: "Leverage ready-to-use RESTful or GraphQL endpoints to access your commodity and energy data, making system integration straightforward.",
      illustration: (
        <div>
          
        </div>
      )
    }
  ]

  return (
    <section className="pt-0 pb-24 px-4 bg-gray-50 dark:bg-black relative">
      <WaveBackground />
      <div className="max-w-7xl mx-auto relative">
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature, i) => (
            <Card 
              key={i} 
              className={`border-gray-100 hover:border-gray-200 bg-white dark:bg-gray-800 dark:border-gray-700 dark:text-gray-200 transition-colors ${
                feature.wide ? 'sm:col-span-2 lg:col-span-2' : ''
              }`}
            >
              <CardHeader>
                <div className="flex items-center gap-2 mb-2">
                  {feature.icon}
                  <CardTitle className="text-lg font-semibold">{feature.title}</CardTitle>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-200">{feature.description}</p>
                {feature.bulletPoints && (
                  <ul className="mt-4 space-y-2">
                    {feature.bulletPoints.map((point, i) => (
                      <li key={i} className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-200">
                        <svg
                          className="h-4 w-4 text-emerald-500 shrink-0"
                          fill="none"
                          strokeWidth="2.5"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                        >
                          <path d="M4.5 12.75l6 6 9-13.5" />
                        </svg>
                        {point}
                      </li>
                    ))}
                  </ul>
                )}
                {feature.badges && (
                  <div className="flex gap-2 mt-4">
                    {feature.badges.map((badge, i) => (
                      <span
                        key={i}
                        className="inline-flex items-center gap-1 text-xs font-medium text-gray-600 bg-gray-100 px-2 py-1 rounded-full"
                      >
                        {badge}
                      </span>
                    ))}
                  </div>
                )}
              </CardHeader>
              <CardContent>{feature.illustration}</CardContent>
            </Card>
          ))}
        </div>
        <p className="text-center mt-12 text-gray-600">
          <span className="font-semibold">Use one or all.</span> Best of breed products. Integrated as a platform.
        </p>
      </div>
    </section>
  )
}